apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    name: apache-deployment
  namespace: modulo-4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      tolerations:
        - key: "hardware"
          operator: "Equal"
          value: "high"
          effect: "NoExecute"
      containers:
      - name: apache
        image: httpd:2.4.63
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
    
