apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    name: registry-deployment
  namespace: modulo-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:3.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: registry-storage
            mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
