kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /var/lib/docker/volumes/kind-pv-registry/_data
    containerPath: /mnt/kind-pv-registry
- role: worker
  extraMounts:
  - hostPath: /var/lib/docker/volumes/kind-pv-registry/_data
    containerPath: /mnt/kind-pv-registry
- role: worker
  extraMounts:
  - hostPath: /var/lib/docker/volumes/kind-pv-registry/_data
    containerPath: /mnt/kind-pv-registry

