apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: modulo-6
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000       # Porta exposta no cluster
      targetPort: 5000 # Porta no container
  type: ClusterIP
